#ifndef SHARED_SHADER 
    #pragma once
#define MPROP_SPEC_POWER 0
#define MPROP_SPEC_THRESH 1
#define MPROP_SPEC_BRIGHTNESS 2

#define MPROP_FRES_POWER 3
#define MPROP_FRES_SCALE 4
#define MPROP_FRES_BRIGHTNESS 5

#define MPROP_TEXSCALE_X 6
#define MPROP_TEXSCALE_Y 7

#define MPROP_R 8
#define MPROP_G 9
#define MPROP_B 10

#define MPROP_VARIATION_FREQUENCY 11
#define MPROP_VARIATION_MIN 12
#define MPROP_VARIATION_MAX 13
#define MPROP_VARIATION_POWER 14

#else
#ifndef MPROP_H
#define MPROP_H
uniform float u_mProps[16];
#define MPROP_SPEC_POWER 0
#define MPROP_SPEC_THRESH 1
#define MPROP_SPEC_BRIGHTNESS 2

#define MPROP_FRES_POWER 3
#define MPROP_FRES_SCALE 4
#define MPROP_FRES_BRIGHTNESS 5

#define MPROP_TEXSCALE_X 6
#define MPROP_TEXSCALE_Y 7

#define MPROP_R 8
#define MPROP_G 9
#define MPROP_B 10

#define MPROP_VARIATION_FREQUENCY 11
#define MPROP_VARIATION_MIN 12
#define MPROP_VARIATION_MAX 13
#define MPROP_VARIATION_POWER 14
#endif

#endif
