#pragma once
const uint8_t WORLD_RESOLUTION = 16;
const uint8_t VOXELS_PER_COORDINATE = WORLD_RESOLUTION * WORLD_RESOLUTION * WORLD_RESOLUTION;
const uint8_t WORLD_COMPUTE_GROUPS = WORLD_RESOLUTION / 8;

const uint8_t DISTANCE_CACHE_SIZE = WORLD_RESOLUTION + 1;
const float COORDINATE_SIZE = 32.0f;
const float VOXEL_SIZE = COORDINATE_SIZE / (WORLD_RESOLUTION - 1);

const uint8_t MAX_X_COORDINATES = 12; 
const uint8_t MAX_Y_COORDINATES = 8;
const uint8_t MAX_Z_COORDINATES = 12; 

const uint8_t MAX_COORDINATE_VERTICES = 4096;
const uint8_t MAX_COORDINATE_INDICES = 16384;
