#pragma once
#define WORLD_RESOLUTION 8
#define VOXELS_PER_COORDINATE (WORLD_RESOLUTION * WORLD_RESOLUTION * WORLD_RESOLUTION)

#define DISTANCE_CACHE_SIZE (WORLD_RESOLUTION + 1)
#define COORDINATE_SIZE 16.0f
#define VOXEL_SIZE (COORDINATE_SIZE / (WORLD_RESOLUTION - 1))

#define MAX_X_COORDINATES 1
#define MAX_Y_COORDINATES 1
#define MAX_Z_COORDINATES 1

#define MAX_COORDINATE_VERTICES 4096
#define MAX_COORDINATE_INDICES 16384

#define COMPUTE_VERTICES_GROUP_SIZE 8
#define VOXELS_PER_COMPUTE (COMPUTE_VERTICES_GROUP_SIZE * COMPUTE_VERTICES_GROUP_SIZE * COMPUTE_VERTICES_GROUP_SIZE)