#pragma once
#define COORDINATE_RESOLUTION 32
#define MESH_ITERATION_SIZE (COORDINATE_RESOLUTION + 1)
#define COORDINATE_SIZE 32.0f
#define VOXEL_SIZE (COORDINATE_SIZE / COORDINATE_RESOLUTION)

#define MAX_X_COORDINATES 8
#define MAX_Y_COORDINATES 1
#define MAX_Z_COORDINATES 8

#define MAX_COORDINATE_VERTICES 4096
#define MAX_COORDINATE_INDICES 16384