#pragma once
#include "DefaultMode.h"
#include "PlanarScaleMode.h"
#include "PlanarTranslateMode.h"
#include "SpawnMode.h"
#include "TerrainTranslateMode.h"
#include "UniformScaleMode.h"
#include "VerticalScaleMode.h"
#include "VerticalTranslateMode.h"
