#pragma once
const int NUM_FRAGMENT_SHADERS = 28;
const char FRAGMENT_SHADERS[NUM_FRAGMENT_SHADERS][32] = {
	"fs_depth_s",
	"fs_postprocess",
	"fs_depth_masked_s",
	"fs_leaves_strand",
	"fs_color_masked",
	"fs_dfsa",
	"fs_dfsa_color",
	"fs_dfsa_color_masked",
	"fs_dfsa_variation",
	"fs_aura",
	"fs_persist",
	"fs_color",
	"fs_color_front",
	"fs_selected_unshaded",
	"fs_selected",
	"fs_selected_front",
	"fs_coveragebar",
	"fs_terraincursor",
	"fs_dfsa_color_terrainclipped",
	"fs_particle",
	"fs_seed",
	"fs_seed_s",
	"fs_text",
	"fs_uibar",
	"fs_flower_test",
	"fs_terrain",
	"fs_blit",
	"fs_hole",
};
