#pragma once
const int NUM_VERTEX_SHADERS = 25;
const char VERTEX_SHADERS[NUM_VERTEX_SHADERS][32] = {
	"vs_inst_billboard_s",
	"vs_inst_s",
	"vs_screenquad",
	"vs_static_s",
	"vs_skeletal_s",
	"vs_inst",
	"vs_particle_stretch",
	"vs_particle_trail",
	"vs_glyph",
	"vs_particle",
	"vs_skeletal",
	"vs_static",
	"vs_coveragebar",
	"vs_inst_billboard",
	"vs_spread",
	"vs_spread_activeonly",
	"vs_spread_activeonly_s",
	"vs_spread_inactiveonly",
	"vs_spread_inactiveonly_s",
	"vs_spread_s",
	"vs_terrain_s",
	"vs_terrainaligned",
	"vs_uirect",
	"vs_worldtext",
	"vs_terrain",
};
